### ISSUE TITLE
( 3 ) Questions about Multiple Pubkeys / Adresses  Before Converting them ...?

### ISSUE THREAD

**Issue by dragonhlf8** [xdsswar/KeyHuntModified#1]
Question 1: -  Should i include all pubkeys in " Pubkeys_in.txt" without ( Prefix 02/03 ) ... or only in single mod ?
Question 2 - also what should if i wanna make it random '' -r ? -R ? or whats that -r 250/100 ? '' 
Question 3 - for Mod '' Adresses '' should i put only The Compressed BTC Adresses in addresses_in.txt even they almost seems similaire ....? example this is compressed" 1F1T1cdb6xkwCua6m3TKgASXUEq2PsECBn" this is the uncompressed 1EeAxcprB2PpCnr34VfZdFrkUWuxyiNEFv ' almost similaire to identify .

**Comment by xdsswar** [comment]
Hi, you should ask to the author of the program, Im about to port it and add some features, but Im very busy right now at my job.  Sorry for the inconvenient.

**Comment by dragonhlf8** [comment]
Pls Easy Question about Multiple Pubkeys_to_xpoints Before Converting them ...? : i hope you answer me  . .Just for Public-Keys  Should i include all the pubkeys in my text file " Pubkeys_in.txt" without ( Prefix 02/03 ) ... or thats only in for single mod ?

**Comment by xdsswar** [comment]
Refer to the Readme on the original repo https://github.com/albertobsd/keyhunt , there you have all you need. I don't remember exactly  but you can specify compressed or uncompressed using the -l param like 
`-l compressed`  for compressed and `-l uncompressed`.
